# Generated by Django 4.2.7 on 2023-11-21 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='poster_url',
            field=models.FileField(blank=True, null=True, upload_to='posters/'),
        ),
    ]
