# Generated by Django 4.2.7 on 2023-11-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_userprofile_language_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='instructor_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
