# Generated by Django 4.2.7 on 2023-11-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_lesson_instructor_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourse',
            name='course',
        ),
        migrations.AddField(
            model_name='usercourse',
            name='course',
            field=models.ManyToManyField(to='main.course'),
        ),
    ]
