# Generated by Django 4.2.7 on 2023-11-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_userprofile_language_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_teacher',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[(1, 'Student'), (2, 'Instructor')], max_length=20, null=True),
        ),
    ]
