# Generated by Django 4.2.7 on 2023-11-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_coursemodule_course_alter_lesson_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='poster_url',
            field=models.FileField(default='settings.MEDIA_ROOT/media/posters/img7.png', upload_to='posters/'),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='poster_url',
            field=models.FileField(default='settings.MEDIA_ROOT/media/posters/img7.png', upload_to='posters/'),
        ),
    ]
