# Generated by Django 4.2.7 on 2023-11-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_course_poster_url_coursemodule_poster_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='poster_url',
            field=models.FileField(default='posters/img7.png', upload_to='posters/'),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='poster_url',
            field=models.FileField(default='posters/img7.png', upload_to='posters/'),
        ),
    ]
