# Generated by Django 4.2.7 on 2023-11-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_course_poster_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='poster_url',
            field=models.FileField(default='img7.png', upload_to='posters/'),
        ),
    ]
